[package]
name = "sinojsonutil"
version = "0.1.0"
authors = ["Colin Redman <20376935+credman0@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
sinoalice_core = { path = "../sinoalice_core" }
serde_json = "1.0"
lazy_static = "1.4.0"

