[package]
name = "sinoalice-db-parser"
version = "0.1.0"
authors = ["Colin Redman <20376935+credman0@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
soup = "0.5"
sinoalice_core = {path = "../sinoalice_core"}
serde_json = "1.0"

